#!/usr/bin/env python3
"""make_round_prompt.py — generate a stage prompt for Claude.

Usage:
    python3 tools/paper_repro/make_round_prompt.py --paper ccws --stage 05_focused_validation
    python3 tools/paper_repro/make_round_prompt.py --paper ccws --stage 05_focused_validation --round AI

Output: prompt text printed to stdout (copy-paste to Claude).
"""

import argparse
import os
import sys

try:
    import yaml
    HAS_YAML = True
except ImportError:
    HAS_YAML = False


SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))


def load_yaml(path):
    if not os.path.exists(path):
        return {}
    if HAS_YAML:
        with open(path) as f:
            return yaml.safe_load(f) or {}
    # Fallback: return raw text as a single key
    with open(path) as f:
        return {"_raw": f.read()}


def load_text(path):
    if not os.path.exists(path):
        return f"[FILE NOT FOUND: {path}]"
    with open(path) as f:
        return f.read()


def format_paper_summary(paper):
    if not paper:
        return "(paper config not loaded)"
    if "_raw" in paper:
        return paper["_raw"]
    lines = []
    for k in ("paper_key", "title", "branch", "final_tag"):
        if k in paper:
            lines.append(f"  {k}: {paper[k]}")
    if "known_approximations" in paper:
        lines.append("  known_approximations:")
        for a in paper["known_approximations"]:
            if isinstance(a, dict):
                lines.append(f"    - {a.get('id', '')}: {a.get('description', '')}")
    if "success_rules" in paper:
        lines.append("  success_rules:")
        for r in paper["success_rules"]:
            if isinstance(r, dict):
                lines.append(f"    - {r.get('id', '')}: {r.get('description', '')}")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate stage prompt for Claude")
    parser.add_argument("--paper", required=True, help="Paper key (e.g. ccws)")
    parser.add_argument("--stage", required=True, help="Stage name (e.g. 05_focused_validation)")
    parser.add_argument("--round", default="", help="Round label (e.g. AI, AK)")
    args = parser.parse_args()

    paper_path = os.path.join(SCRIPT_DIR, "papers", f"{args.paper}.yaml")
    template_path = os.path.join(SCRIPT_DIR, "templates", f"{args.stage}.md")

    paper = load_yaml(paper_path)
    template = load_text(template_path)
    paper_summary = format_paper_summary(paper)

    round_label = args.round if args.round else f"<next round for {args.stage}>"

    prompt = f"""# Paper Reproduction Prompt
# Paper: {args.paper}  Stage: {args.stage}  Round: {round_label}
# Generated by: tools/paper_repro/make_round_prompt.py
# -------------------------------------------------------

## Paper Config Summary
{paper_summary}

## Stage Instructions
{template}

## Standard Rules (apply to every round)
- 不改 src/（除非本 stage 明确允许）
- 不自动 commit / tag / push
- 不运行 /save-session
- 用中文输出，专有名词、函数名、文件名保持英文
- 如果执行超过 10 分钟，暂停并输出 checkpoint summary
- 每轮结束必须更新 experiments/paper-{args.paper}/round_state.yaml

## Pre-flight Check
在开始前运行：
  bash tools/paper_repro/check_repo_clean.sh {paper.get('branch', '<branch>')} {paper.get('final_tag', '')}
如果不通过，停止并报告原因。
"""

    print(prompt)


if __name__ == "__main__":
    main()
